CREATE SCHEMA IF NOT EXISTS retail_banking;

CREATE TABLE retail_banking.users (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      created_at timestamp(6) NOT NULL,
                                      email varchar(255) NOT NULL,
                                      full_name varchar(255) NOT NULL,
                                      "password" varchar(255) NOT NULL,
                                      "role" varchar(255) NOT NULL,
                                      email_verified bool NOT NULL,
                                      CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
                                      CONSTRAINT users_pkey PRIMARY KEY (id),
                                      CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE retail_banking.audit_logs (
                                           id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                           "action" varchar(255) NOT NULL,
                                           created_at timestamp(6) NOT NULL,
                                           description varchar(500) NOT NULL,
                                           performed_by varchar(255) NOT NULL,
                                           "role" varchar(255) NOT NULL,
                                           CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
                                           CONSTRAINT audit_logs_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE retail_banking.accounts (
                                         id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                         account_number varchar(20) NOT NULL,
                                         account_status varchar(255) NOT NULL,
                                         account_type varchar(255) NOT NULL,
                                         branch_name varchar(255) NOT NULL,
                                         created_at timestamp(6) NOT NULL,
                                         current_balance numeric(38, 2) NOT NULL,
                                         user_id int8 NOT NULL,
                                         CONSTRAINT accounts_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'FROZEN'::character varying])::text[]))),
	CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'CURRENT'::character varying])::text[]))),
	CONSTRAINT accounts_pkey PRIMARY KEY (id),
	CONSTRAINT uk6kplolsdtr3slnvx97xsy2kc8 UNIQUE (account_number),
	CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES retail_banking.users(id)
);

CREATE TABLE retail_banking.cards (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      card_holder_name varchar(255) NOT NULL,
                                      card_number varchar(16) NOT NULL,
                                      card_status varchar(255) NOT NULL,
                                      card_type varchar(255) NOT NULL,
                                      cvv varchar(3) NOT NULL,
                                      daily_limit numeric(38, 2) NOT NULL,
                                      expiry_date date NOT NULL,
                                      account_id int8 NOT NULL,
                                      CONSTRAINT cards_card_status_check CHECK (((card_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'FROZEN'::character varying, 'BLOCKED'::character varying])::text[]))),
	CONSTRAINT cards_card_type_check CHECK (((card_type)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying])::text[]))),
	CONSTRAINT cards_pkey PRIMARY KEY (id),
	CONSTRAINT ukqualp9iflk959u561wanavuj1 UNIQUE (card_number),
	CONSTRAINT fkdjw7dinkpc0f01yk4m57uq2u2 FOREIGN KEY (account_id) REFERENCES retail_banking.accounts(id)
);

CREATE TABLE retail_banking.fixed_deposits (
                                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                               closed_date date NULL,
                                               created_at timestamp(6) NOT NULL,
                                               deposit_amount numeric(38, 2) NOT NULL,
                                               deposit_date date NOT NULL,
                                               fd_number varchar(20) NOT NULL,
                                               interest_rate numeric(38, 2) NOT NULL,
                                               maturity_amount numeric(38, 2) NOT NULL,
                                               maturity_date date NOT NULL,
                                               status varchar(255) NOT NULL,
                                               tenure_years int4 NOT NULL,
                                               source_account_id int8 NOT NULL,
                                               user_id int8 NOT NULL,
                                               CONSTRAINT fixed_deposits_pkey PRIMARY KEY (id),
                                               CONSTRAINT fixed_deposits_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PREMATURELY_CLOSED'::character varying, 'MATURED_CLOSED'::character varying])::text[]))),
	CONSTRAINT uk5kiyhfr7ce2gksvh0unlpgnyg UNIQUE (fd_number),
	CONSTRAINT fko3c5906adf7axdl4y3bfahx07 FOREIGN KEY (user_id) REFERENCES retail_banking.users(id),
	CONSTRAINT fktkh8wqlvqtxgd4hnho5nqlbhr FOREIGN KEY (source_account_id) REFERENCES retail_banking.accounts(id)
);

CREATE TABLE retail_banking.kyc_documents (
                                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                              content_type varchar(255) NOT NULL,
                                              document_type varchar(255) NOT NULL,
                                              file_size int8 NOT NULL,
                                              kyc_verification_status varchar(255) NOT NULL,
                                              original_file_name varchar(255) NOT NULL,
                                              storage_path varchar(255) NOT NULL,
                                              stored_file_name varchar(255) NOT NULL,
                                              uploaded_at timestamp(6) NOT NULL,
                                              user_id int8 NOT NULL,
                                              rejection_reason varchar(500) NULL,
                                              CONSTRAINT kyc_documents_document_type_check CHECK (((document_type)::text = ANY ((ARRAY['PAN'::character varying, 'AADHAAR'::character varying])::text[]))),
	CONSTRAINT kyc_documents_kyc_verification_status_check CHECK (((kyc_verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[]))),
	CONSTRAINT kyc_documents_pkey PRIMARY KEY (id),
	CONSTRAINT uklpthcxvvsodux8l781p3i283w UNIQUE (stored_file_name),
	CONSTRAINT fkllb8bcbbyo994afdepf7f7j63 FOREIGN KEY (user_id) REFERENCES retail_banking.users(id)
);

CREATE TABLE retail_banking.loans (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      annual_interest_rate numeric(5, 2) NOT NULL,
                                      created_at timestamp(6) NOT NULL,
                                      loan_number varchar(255) NOT NULL,
                                      loan_type varchar(255) NOT NULL,
                                      monthly_emi numeric(15, 2) NOT NULL,
                                      next_due_date date NULL,
                                      principal_amount numeric(15, 2) NOT NULL,
                                      remaining_balance numeric(15, 2) NOT NULL,
                                      start_date date NULL,
                                      status varchar(255) NOT NULL,
                                      tenure_months int4 NOT NULL,
                                      account_id int8 NOT NULL,
                                      user_id int8 NOT NULL,
                                      rejection_remarks varchar(500) NULL,
                                      CONSTRAINT loans_loan_type_check CHECK (((loan_type)::text = ANY ((ARRAY['PERSONAL'::character varying, 'HOME'::character varying, 'VEHICLE'::character varying])::text[]))),
	CONSTRAINT loans_pkey PRIMARY KEY (id),
	CONSTRAINT loans_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'ACTIVE'::character varying, 'PAID_OFF'::character varying])::text[]))),
	CONSTRAINT ukn0f0lgenbr3aknq9eahpk3los UNIQUE (loan_number),
	CONSTRAINT fk6xxlcjc0rqtn5nq28vjnx5t9d FOREIGN KEY (user_id) REFERENCES retail_banking.users(id),
	CONSTRAINT fkeja64hsi0agxgtppa7uccxrh4 FOREIGN KEY (account_id) REFERENCES retail_banking.accounts(id)
);

CREATE TABLE retail_banking.scheduled_transfers (
                                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                    amount numeric(38, 2) NOT NULL,
                                                    created_at timestamp(6) NOT NULL,
                                                    description varchar(255) NULL,
                                                    frequency varchar(255) NOT NULL,
                                                    next_execution_date date NOT NULL,
                                                    recipient_account_number varchar(20) NOT NULL,
                                                    source_account_number varchar(20) NOT NULL,
                                                    status varchar(255) NOT NULL,
                                                    user_id int8 NOT NULL,
                                                    CONSTRAINT scheduled_transfers_frequency_check CHECK (((frequency)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying])::text[]))),
	CONSTRAINT scheduled_transfers_pkey PRIMARY KEY (id),
	CONSTRAINT scheduled_transfers_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT fklt32nwnn39sxpkljbe0q5scx3 FOREIGN KEY (user_id) REFERENCES retail_banking.users(id)
);

CREATE TABLE retail_banking.transactions (
                                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                             amount numeric(38, 2) NOT NULL,
                                             available_balance numeric(38, 2) NOT NULL,
                                             description varchar(255) NULL,
                                             transaction_date timestamp(6) NOT NULL,
                                             transaction_id varchar(36) NOT NULL,
                                             transaction_type varchar(255) NOT NULL,
                                             account_id int8 NOT NULL,
                                             CONSTRAINT transactions_pkey PRIMARY KEY (id),
                                             CONSTRAINT transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying])::text[]))),
	CONSTRAINT uk6plyfbm3wy6ds7hongoml5xbk UNIQUE (transaction_id),
	CONSTRAINT fk20w7wsg13u9srbq3bd7chfxdh FOREIGN KEY (account_id) REFERENCES retail_banking.accounts(id)
);

CREATE TABLE retail_banking.verification_tokens (
                                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                    created_at timestamp(6) NOT NULL,
                                                    expiry_date timestamp(6) NOT NULL,
                                                    "token" varchar(255) NOT NULL,
                                                    used bool NOT NULL,
                                                    user_id int8 NOT NULL,
                                                    token_type varchar(255) NULL,
                                                    CONSTRAINT uk6q9nsb665s9f8qajm3j07kd1e UNIQUE (token),
                                                    CONSTRAINT verification_tokens_pkey PRIMARY KEY (id),
                                                    CONSTRAINT verification_tokens_token_type_check CHECK (((token_type)::text = ANY ((ARRAY['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[]))),
	CONSTRAINT fk54y8mqsnq1rtyf581sfmrbp4f FOREIGN KEY (user_id) REFERENCES retail_banking.users(id)
);

CREATE TABLE retail_banking.loan_repayments (
                                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                                amount_paid numeric(15, 2) NOT NULL,
                                                interest_component numeric(15, 2) NOT NULL,
                                                payment_date timestamp(6) NOT NULL,
                                                principal_component numeric(15, 2) NOT NULL,
                                                remaining_loan_balance numeric(15, 2) NOT NULL,
                                                transaction_reference varchar(255) NOT NULL,
                                                loan_id int8 NOT NULL,
                                                CONSTRAINT loan_repayments_pkey PRIMARY KEY (id),
                                                CONSTRAINT fkmvfjvk48bhsvwbdis0s9uwn1t FOREIGN KEY (loan_id) REFERENCES retail_banking.loans(id)
);