springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true

spring:
  sql:
    init:
      mode: always

app:
  email-verification:
    enabled: false

  kyc:
    notification-enabled: false

  storage:
    type: local