springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true

app:
  jwt-secret: bankflow-development-key-must-be-replaced-before-production-2026

  default-admin:
    full-name: System Administrator
    email: admin@bankflow.com
    password: AdminSecretPass123!